// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffzjujkfxfnptfnvdiqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmemp1amtmeGZucHRmbnZkaXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjEzOTEsImV4cCI6MjA2NDkzNzM5MX0.BPWurCzR_rWliEdku2rpu97EL_4KUV_tAPKy-UI94_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);